# Generated by Django 3.2.8 on 2021-11-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_pharmacie_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='pharmacie',
        ),
    ]
