# Generated by Django 3.2.8 on 2021-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211130_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='etat',
            field=models.CharField(default='true', max_length=50),
        ),
    ]
