# Generated by Django 3.2.8 on 2021-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etat',
            name='medicament',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='etat',
            name='pharmacie',
            field=models.CharField(max_length=1),
        ),
    ]
