# Generated by Django 3.2.8 on 2021-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20211202_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etat',
            name='medicament',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etat',
            name='pharmacie',
            field=models.IntegerField(),
        ),
    ]
