# Generated by Django 3.2.8 on 2021-12-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20211202_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
