-- MySQL Script generated by MySQL Workbench
-- Sat Oct  2 19:21:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dawinidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dawinidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dawinidb` DEFAULT CHARACTER SET utf8 ;
USE `dawinidb` ;

-- -----------------------------------------------------
-- Table `dawinidb`.`coordonnees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`coordonnees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `pharmacies_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`dates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `debut` DATETIME NULL,
  `fin` DATETIME NULL,
  `medicaments_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`dates_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`dates_base` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `debut` DATETIME NULL,
  `fin` DATETIME NULL,
  `medicaments_base_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`medicaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`medicaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `etat` ENUM('0', '1') NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`medicaments_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`medicaments_base` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`pharmacies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`pharmacies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `pseudo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `quartier` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`pharmacies_has_medicaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`pharmacies_has_medicaments` (
  `pharmacies_id` INT NOT NULL,
  `medicaments_id` INT NOT NULL,
  PRIMARY KEY (`pharmacies_id`, `medicaments_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dawinidb`.`telephones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dawinidb`.`telephones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primaire` VARCHAR(45) NULL,
  `secondaire` VARCHAR(45) NULL,
  `whatsapp` VARCHAR(45) NULL,
  `pharmacies_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
