# Generated by Django 3.2.8 on 2021-10-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_nom', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
                ('pharmacie_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.CharField(default='', max_length=50)),
                ('fin', models.CharField(default='', max_length=50)),
                ('medicament_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dates_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.CharField(default='', max_length=50)),
                ('fin', models.CharField(default='', max_length=50)),
                ('medicament_base_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prix', models.IntegerField(default='')),
                ('code', models.CharField(default='', max_length=50)),
                ('etat', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('pharmacie_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prix', models.IntegerField(default='')),
                ('code', models.CharField(default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('pseudo', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('quartier', models.CharField(blank=True, default='Basra', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaire', models.CharField(blank=True, default='', max_length=50)),
                ('secondaire', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('pharmacie_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(default='', max_length=100)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.a')),
            ],
        ),
    ]
