# Generated by Django 3.2.8 on 2021-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b',
            old_name='b',
            new_name='b_nom',
        ),
        migrations.AddField(
            model_name='a',
            name='a_age',
            field=models.CharField(default='', max_length=100),
        ),
    ]
