# Generated by Django 3.2.8 on 2021-10-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
