# Generated by Django 3.2.8 on 2021-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_pharmacie_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
