# Generated by Django 3.2.8 on 2021-10-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
    ]
