# Generated by Django 3.2.8 on 2021-10-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_pharmacie_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='etat',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
