# Generated by Django 3.2.8 on 2021-10-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_medicament_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='prix',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
