# Generated by Django 3.2.8 on 2021-10-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicament',
        ),
    ]
